# Generated by Django 3.2.9 on 2021-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dlcs_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
