volumes:
  dlcs_postgres_data: {}
  dlcs_postgres_data_backups: {}

services:
  postgres:
    image: postgres:18
    hostname: postgres
    ports:
      - "5452:5432"
    volumes:
      - dlcs_postgres_data:/var/lib/postgresql/docker
      - dlcs_postgres_data_backups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dlcs_password