services:
  appetiser:
    image: ghcr.io/dlcs/appetiser:pr-25 # TODO - temp use PR until release cut
    ports:
      - "5031:8000"
    volumes:
      - $HOME\Docker\scratch:/scratch
      - ./kdu_src:/kdu_src
    env_file:
      - .env
