version: '3'

services:
  appetiser:
    image: digirati/appetiser:latest
    ports:
      - "5031:80"
    volumes:
      - $HOME\Docker\scratch:/scratch
      - $HOME\.aws:/root/.aws
    env_file:
      - .env
