name: Sync GitHub issues to Jira
on: [issues, issue_comment, pull_request, workflow_dispatch]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/sync-issues-github-jira@v1
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
          label: 'jira'