name: DLCS Run Sonar Analysis

on: workflow_dispatch

jobs:    
  run-sonar-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/protagonist
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "protagonist.sln"
    steps:   
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - id: checkout
        uses: actions/checkout@v4
      - id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Install SonarCloud scanners and code coverage tools
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet new tool-manifest
          dotnet tool install --local JetBrains.dotCover.CommandLineTools
      - id: restore-dotnet-dependencies
        run: dotnet restore $SOLUTION
      - id: build-dotnet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"dlcs_protagonist" /o:"dlcs" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html
          dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
          dotnet dotcover cover-dotnet --Output dotcover.result.html --ReportType=HTML -- test --filter 'Category!=Manual' --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"